spring.application.name=E-library


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/elibrary
spring.datasource.username=root
spring.datasource.password=rupa2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Server Port
server.port=8030